### ISSUE TITLE
Application shells with search input missing form tag

### ISSUE THREAD

**Issue by jreviews** [tailwindui/issues#116]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar
- Component name: All components with search input

**Describe the bug**
The search input is missing a wrapping `<form>` tag needed to automatically submit the form on `enter`.

**Comment by jreviews** [comment]
@adamwathan Not sure if this is covered somewhere. When you close an issue without a comment, what should we assume? It's not considered an issue? Or it will be fixed?

**Comment by adamwathan** [comment]
Hey sorry about that! It was closed because I merged a PR in the actual Tailwind UI repo that fixed the issue, so GitHub auto-closed it because they were linked:

![image](https://user-images.githubusercontent.com/4323180/86818425-5ee3e180-c054-11ea-9d4b-f6fcfb8c0122.png)

Will be fixed on the live site next time we deploy 👍
