### ISSUE TITLE
Pull in SVGs via URL rather than embedding full text

### ISSUE THREAD

**Issue by lucperkins** [tailwindui/issues#126]
I think it'd be strongly preferable to pull in SVGs in the Tailwind UI example components via an external URL (e.g. a GitHub "raw" content URL) rather than embedding the full text of the component. This would have three benefits:

1. The example component HTML would be more compact (while still working immediately upon copy/paste).
2. The example component HTML would be easier to read (in some components the SVG text comprises a large % of the total text).
3. It'd be easier to remove the placeholder SVGs in favor of user-chosen SVGs.

**Comment by adamwathan** [comment]
Hey @lucperkins thanks for the suggestion! The main reason we use inline SVG as opposed to an `img` tag because it's the only way you can actually customize the colors of the icons.

This won't work for example, the icon will just be black:

```html
<img src="/some-icon.svg" class="text-red-500">
```

So no plans to change this right now unless there's an approach I'm missing that would still let you style the icons with utilities.

**Comment by lucperkins** [comment]
@adamwathan Ah yes, makes perfect sense.
