### ISSUE TITLE
Select: Dotted border outline border in Firefox

### ISSUE THREAD

**Issue by KarelVerschraegen** [tailwindui/issues#136]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: Select (Country / Region)

**Describe the bug**
The select shows a dotted outline when focused in Firefox

**To Reproduce**
1. Go to 'https://tailwindui.com/components/application-ui/forms/form-layouts'
2. Click on 'Country / Region select' in Firefox
3. See the dotted outline around 'United States'

**Expected behavior**
The dotted outline is not visible. This behaviour does not happen in Chrome.

**Screenshots**
![test](https://user-images.githubusercontent.com/11301291/78543663-4536c200-77f9-11ea-90c7-193fb799b797.png)

**Browser/Device (if applicable)**
 - OS: Linux
 - Browser Firefox
 - Version https://tailwindui.com/components/application-ui/forms/form-layouts

**Additional context**
Related issues:
https://stackoverflow.com/questions/19451183/cannot-remove-outline-dotted-border-from-firefox-select-drop-down

https://github.com/jgthms/bulma/issues/1219

Adding this to the component hides the dotted outline after focus, but it is still visible for a split second
```
select:-moz-focusring {
    color: transparent;
    text-shadow: 0 0 0 #000;
}
```

**Comment by jasonlbeggs** [comment]
This is an issue in most CSS frameworks including Bootstrap 4. It's probably best to just include the CSS snippet you mentioned in your project, but if you would like to discuss it further, I would open an issue on the [Tailwind Custom Forms plugin repo](https://github.com/tailwindcss/custom-forms) (the underlying forms plugin used in Tailwind UI). I'm going to close the issue for here since it's not really a bug in Tailwind UI. Thanks!
