### ISSUE TITLE
Table components overflow property cuts off dropdown component

### ISSUE THREAD

**Issue by shanedasilva** [tailwindui/issues#147]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/tables/wide
- Component name:  Wide Tables

**Describe the bug**
In the example component there is an "Edit" button as the right most table column. When using that button the trigger a dropdown component, the dropdown over the last few table rows is cut off due the the overflow `hidden property` on the table component

**Expected behavior**
The dropdown component opens and is not cut off by the boundaries of the table component

**Screenshots**
Notice the dropdown that is opened on the second to last table row with the name "Certificate Type 2"

![Screen Shot 2020-04-13 at 7 03 34 PM](https://user-images.githubusercontent.com/1010309/79178224-8743a300-7db9-11ea-82d4-102d3ce6e74d.png)

**Browser/Device (if applicable)**
 - OS: macOS Catalina
 - Browser Chrome
 - Version 80.0.3987.163

**Comment by jasonlbeggs** [comment]
In this instance, you should remove the overflow-hidden class and add `rounded-b-lg` to the last `<tr>` in the table or `tbody` (whichever has a background color set). The overflow-hidden is there so the `tr` or `tbody` background doesn't overflow the rounded corners at the bottom of the card. Let me know if that doesn't make sense. Thanks!

**Comment by ExiaSR** [comment]
@jasonlbeggs 

Removing the `overflow-hidden` only allows the dropdown menu of the last row to be visible with scrolling.

In order to get rid of the vertical scrolling, the class `overflow-x-auto` from the outer div needs to be changed to `overflow-x-visible`. However, this also breaks the rounded corner of the table, which only works when the parent `div` is set to `overflow: hidden`. Any suggestion?

**Comment by thannaske** [comment]
I ran into the same issue as well.

**Comment by rodrigore** [comment]
+1

**Comment by thannaske** [comment]
I'm a little disappointed that this issue isn't getting any further treatment at all. As I can see the home screen example "Full-width with sidebar" doesn't run into this issue, so something was fixed but this correction was not applied to the existing table examples.

**Comment by adamwathan** [comment]
The best solution is to use portals to render the dropdown contents, so that they are rendered outside of the table. Otherwise any parent with overflow set will cause the dropdown to be chopped off. For the full page example we were able to remove overflow-x-auto from the table because we didn't want it to scroll horizontally.

It's not possible to make the table scroll horizontally and avoid the dropdowns getting cropped without rendering the dropdowns outside of the table using portals or a similar technique. I'll make a note to add some extra table examples that don't use horizontal scrolling so there's a simple option for people who don't want to use the portal approach.

**Comment by rodrigore** [comment]
@adamwathan  which portal library do you recommend to use with vanilla js?  I only found for  [vue](https://github.com/LinusBorg/portal-vue)

**Comment by adamwathan** [comment]
With vanilla JS you don't really need any library, you just need to move the dropdown panel to the bottom of your document (right before the closing body tag) and toggle its visibility there so it's not affected by the styles of any parents. You'll want to use a library like Popper.js to make sure it's positioned correctly but you don't actually need a true portal since you are in total control of where things are rendered anyways 👍🏻

Hope that helps!

**Comment by rodrigore** [comment]
Thank you, I will give a try

**Comment by NickJorens** [comment]
I just wanted to chime in for any one stuck on the same issue. I'm using TailwindCSS 2.
I was stuck on this issue, and thanks to the comment above I was able to come up with this solution. No more overflow issues when using TailwindUI [panels](https://tailwindui.com/components/application-ui/layout/panels) or [tables](https://tailwindui.com/components/application-ui/lists/tables)! :fire: :exploding_head: 


### Result
![image](https://user-images.githubusercontent.com/7328317/101169874-e2beeb80-363d-11eb-948f-8a87016e7dec.png)


### HTML
```javascript
<div x-data="dropdown()" x-init="Popper.createPopper($el, $refs.popover, { placement: 'bottom'});">
    <div class="relative inline-block text-left">
        <div x-spread="trigger">
            <button type="button"
                    class="inline-flex justify-center w-full shadow-sm px-4 py-2 bg-white ..."
                    id="options-menu" aria-haspopup="true" aria-expanded="true">Options
                <i class="fal fa-chevron-down -mr-1 ml-2 h-5 w-5"></i>
            </button>
        </div>
    </div>
    <div x-spread="dialogue"
         x-ref="popover"
         x-cloak
         class="mt-8 w-56 rounded-md shadow-lg bg-white absolute z-50 ..."
         role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
        <div class="py-1">
            <a href="#"
               class="..."
               role="menuitem">
                Edit
            </a>
        </div>
    </div>
</div>
```

### Alpine [object destructuring](https://github.com/alpinejs/alpine#x-data)

```javascript
window.dropdown = function () {
    return {
        open: false,
        trigger: {
            ['@click']() {
                this.open = true
            },
            ['@focus']() {
                this.open = true
            },
            ['@keydown']() {
                this.open = true
            },
        },
        dialogue: {
            ['x-show']() {
                return this.open
            },
            ['@click.away']() {
                this.open = false
            },
        }
    }
}
```

**Comment by neontuna** [comment]
After spending an inordinate amount of time trying to get this working in Vuejs 2 today I wanted to share my results for anyone else struggling.  Using [Popperjs](https://popper.js.org) for this kept rendering the dropdown off screen until I found that I needed to call `this.popperInstance.update()` when showing the dropdown in order to get it position correctly.  Which doesn't make sense to me because I'm using the `v-show` directive which should be rendering the element in the DOM, just hidden.  Anyway here's the .vue component, also handles clicking outside the dropdown to close it.

```javascript
<template>
  <div>
    <div @click="toggle()" ref="button">
      <slot name="dropdown-button"></slot>
    </div>
    <div class="z-10" ref="content">
      <transition
        enter-active-class="transition duration-100 ease-out"
        enter-class="transform scale-75 opacity-0"
        enter-to-class="transform scale-100 opacity-100"
        leave-active-class="transition duration-75 ease-in"
        leave-class="transform scale-100 opacity-100 "
        leave-to-class="transform scale-75 opacity-0"
      >
        <div v-show="isOpen" class="w-56 bg-white rounded-md shadow-lg ring-1 ring-black ring-opacity-5">
          <div class="py-1" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
            <slot name="dropdown-content"></slot>
          </div>
        </div>
      </transition>
    </div>
  </div>
</template>

<script>
import { createPopper } from '@popperjs/core';

export default {
  data() {
    return {
      isOpen: false,
      popperInstance: null,
    }
  },
  methods: {
    close (event) {
      if (!this.$el.contains(event.target)) {
        this.isOpen = false;
      }
    },
    toggle () {
      this.isOpen = !this.isOpen;
      this.popperInstance.update();
    },
  },
  mounted () {
    document.addEventListener('click', this.close);

    this.popperInstance = createPopper(this.$refs["button"], this.$refs["content"], {
      placement: 'bottom-end',
      modifiers: [
        {
          name: 'offset',
          options: {
            offset: [0, 4],
          },
        },
      ],
    });
  },
  beforeDestroy () {
    document.removeEventListener('click',this.close);

    if (this.popperInstance) {
      this.popperInstance.destroy();
      this.popperInstance = null;
    }
  }
}
</script>

<style>
</style>
```

And then in the parent component 
```html
<Dropdown>
  <template v-slot:dropdown-button>
    <button type="button" class="inline-flex justify-center w-full px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-indigo-500" id="options-menu" aria-haspopup="true" aria-expanded="true">
      Actions
      <!-- Heroicon name: chevron-down -->
      <svg class="w-5 h-5 ml-2 -mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
      </svg>
    </button>
  </template>
  <template v-slot:dropdown-content>
    <a href="#"class="flex items-center px-4 py-2 text-sm text-gray-700 group hover:bg-gray-100 hover:text-gray-900" role="menuitem">
      Link A
    </a>
    <a href="#"class="flex items-center px-4 py-2 text-sm text-gray-700 group hover:bg-gray-100 hover:text-gray-900" role="menuitem">
      Link B
    </a>
    <a href="#"class="flex items-center px-4 py-2 text-sm text-gray-700 group hover:bg-gray-100 hover:text-gray-900" role="menuitem">
      Link C
    </a>
  </template>
</Dropdown>
```

**Comment by develar** [comment]
Solution for Vue 3 is located in the headlessui examples.

See https://github.com/tailwindlabs/headlessui/blob/d25f80ae9d896446c2b7119a70cfd5d99e250050/packages/%40headlessui-vue/examples/src/components/popover/popover.vue#L79, https://github.com/tailwindlabs/headlessui/blob/d25f80ae9d896446c2b7119a70cfd5d99e250050/packages/%40headlessui-vue/examples/src/components/popover/popover.vue#L138 and https://github.com/tailwindlabs/headlessui/blob/d25f80ae9d896446c2b7119a70cfd5d99e250050/packages/%40headlessui-vue/examples/src/playground-utils/hooks/use-popper.js#L4

TypeScript version of `usePopper`:

```ts
import { createPopper } from "@popperjs/core"
import { OptionsGeneric } from "@popperjs/core/lib/types"
import { ref, onMounted, watchEffect, Ref } from "vue"

// https://github.com/tailwindlabs/tailwindui-issues/issues/147
export function usePopper(options: Partial<OptionsGeneric<Partial<unknown>>>): { trigger: Ref<HTMLElement | null>; popper: Ref<HTMLElement | null> } {
  const trigger = ref<HTMLElement | null>(null)
  const popper = ref<HTMLElement | null>(null)

  onMounted(() => {
    watchEffect(onInvalidate => {
      const popperValue = popper.value as HTMLElement & { el?: HTMLElement } | null
      const triggerValue = trigger.value as HTMLElement & { el?: HTMLElement } | null
      const popperEl = popperValue?.el ?? popperValue
      const referenceElement = triggerValue?.el ?? triggerValue
      if (!(referenceElement instanceof HTMLElement) || !(popperEl instanceof HTMLElement)) {
        return
      }

      const {destroy} = createPopper(referenceElement, popperEl, options)
      onInvalidate(destroy)
    })
  })

  return {trigger, popper}
}
```

In a setup script of a Vue 3 component:

```
const {trigger : popoverButton, popper : popoverPanel} = usePopper({
   placement: "auto",
   strategy: "fixed",
 })
```

Wrap `PopoverPanel` into `Portal`.
If you use transition, wrap `PopoverPanel` into additional `div`: `<div ref="popoverPanel">`.

Tailwind is a great product. It allows me to avoid using full-blown UI framework like Ant Design or Element Plus.

**Comment by jarnesjo** [comment]
React + Popper.js example can be find here https://github.com/tailwindlabs/headlessui/blob/259965546beafa633f13973f05c2704f08ace620/packages/%40headlessui-react/pages/menu/menu-with-popper.tsx

**Comment by nadenf** [comment]
In case anyone sees this in the future. This solution worked for me without needing Popper:

https://stackoverflow.com/questions/69565557/tailwind-css-overflow-dropdown-issue

You can just manually add the borders manually to each of the tr/td corners of the table.

**Comment by zulkufdemirhan** [comment]
Do not modify other class properties found in Tailwind UI designs. When you add only the **'bottom-0'** class to the dropdown menu component, the issue is resolved. Additionally, this solution ensures smooth responsive design without any issues.

 ```
<div class="relative inline-block text-left">
  <div 
    class="hidden absolute right-8 bottom-0 z-10 mt-2 w-56 origin-top-right divide-y divide-gray-100 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" 
    role="menu" 
    data-dropdown-target="menu"
    aria-orientation="vertical" aria-labelledby="table-dropdown">
    <div role="none">
      {YOUR CONTENT}
    </div>
  </div>
</div>
```
**Before The Solution:**
<img width="383" alt="Screenshot 2023-12-15 at 13 11 18" src="https://github.com/tailwindlabs/tailwindui-issues/assets/95721351/a0fb0822-ae44-4df9-8f41-6492433a68c1">

**After The Solution:**
<img width="385" alt="Screenshot 2023-12-15 at 13 10 36" src="https://github.com/tailwindlabs/tailwindui-issues/assets/95721351/3cd19306-8100-46b5-bb0a-095b18014838">

**Comment by shammahk** [comment]
This can be solved with the [HeadlessUI Float Portal](https://headlessui-float.vercel.app/react/portal.html).

You won't need to rewrite so much code and it isn't hacky. [Steps to use](https://headlessui-float.vercel.app/react/quick-start.html)

**Comment by AbdaalHassan** [comment]
.custom-dropdown {
    position: fixed !important;
}
or use Teleport if you are in Vue3

**Comment by usmannaveed1994** [comment]
using Portal & popper.js with React
https://popper.js.org/react-popper/v2/react-portals/
