### ISSUE TITLE
Add title attributes to a tags

### ISSUE THREAD

**Issue by Christophvh** [tailwindui/issues#16]
Hi,

Loving Tailwind UI ! thanks for the great product & amazing pricing.

I have noticed that most <a> tags are missing a title attribute. I think it would be good to add this by default since it pushes developers into good standards, it's good for SEO and screenreaders.

**Comment by adamwathan** [comment]
Hey @Christophvh! I did some digging into this and most resources I'm finding explicitly recommend not using the title attribute on links:

https://silktide.com/blog/2013/i-thought-title-text-improved-accessibility-i-was-wrong
https://a11yproject.com/posts/creating-valid-and-accessible-links/

So I'm going to close this at least for now — anyone using Tailwind UI templates can of course add the title attribute if they want it but since it doesn't seem to be a strong obvious best practice I think it's better to keep them out of the examples.

Thanks for the suggestion 👍
