### ISSUE TITLE
FAQ: centered accordion does not work

### ISSUE THREAD

**Issue by dakira** [tailwindui/issues#35]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/faq-sections
- Component name: Centered Accordion

**Describe the bug**
The JS doesn't seem to work, the individual questions don't unfold when clicked.

**Comment by adamwathan** [comment]
I've updated the example so that expand/collapse works but keep in mind Tailwind UI is very much a "bring-your-own-JavaScript" product and even when we do provide some example JS it's just to show what the component looks like, not to give you a production-ready reference implementation of the JS. You'll want to implement the behavior you need using your JS paradigm of choice, being sure to make things keyboard accessible, maintain the right values in any necessary aria attributes, etc.

**Comment by dakira** [comment]
Thanks Adam. I'm aware of course, just thought you wanted to know. :)
