### ISSUE TITLE
Misspelled w-full class on "Action Panel with Input"

### ISSUE THREAD

**Issue by christopher4lis** [tailwindui/issues#56]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/action-panels
- Component name: With Input

**Describe the bug**
Class within the code is spelled as `w-ful` rather than `w-full`

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7675752/76127636-25309a80-5fd0-11ea-9d91-432c832ed2f8.png)

**Browser/Device (if applicable)**

**Additional context**

**Comment by adamwathan** [comment]
Whoops, this is an artifact of my lazy approach to toggling a class when Steve and I are trying to figure something out in a design — I just delete a character and refresh the page 😅 

Ultimately we decided to not use full-width buttons on action panels, so that class can safely be removed (unless you want to go full-width of course, then add w-full and go for it, it's your component!)

Pushing a fix now 👍
