### ISSUE TITLE
Alpine behavior is causing extra classes to be left over in other frameworks

### ISSUE THREAD

**Issue by bcorcoran** [tailwindui/issues#62]
This is not a bug per se, but an issue with Alpine's behavior. In many examples in Tailwind UI, there is something like the following:

```
<div class="... -translate-x-full" :class="{'translate-x-0': sidebarOpen, '-translate-x-full': !sidebarOpen}">
```

Which, with Alpine, behaves normally. If `sidebarOpen = true`, you have:

```
<div class="... translate-x-0">
```

When `sidebarOpen = false`, it's:

```
<div class="... -translate-x-full">
```

However, when using Vue (I have not tested React or Angular, so forgive me here) if you aren't aware of this behavior and you don't remove `-translate-x-full` from the regular `class=""` declaration, you end up with this when `sidebarOpen = true`:

```
<div class="... -translate-x-full translate-x-0">
```

Which then causes the sidebar not to work. This is not clear behavior, so a note in the docs would be nice to explain that the dynamic classes may need to be removed from the normal class declaration to behave properly in non-Alpine apps.

**Comment by adamwathan** [comment]
Yeah totally see how this could trip you up when translating things. I'm thinking the simplest solution is to just remove the duplicate classes — it would introduce a new issue though where you might see a slight flicker while Alpine "settles" the element's class attribute when booting up :/ I'm not _too_ worried about that since the Alpine demos are meant to be documentation and not actual reference implementations for anyone's real JS, but what do you think? 

Maybe just some documentation about this is a better solution? Maybe both?

**Comment by pdevito3** [comment]
Makes sense to remove it but documentation would be good in case someone were to try and use it as is!

**Comment by bcorcoran** [comment]
It was a really subtle thing (and pretty minor, once I figured out the issue) so I'm really not sure either on the best way to approach this. 

Off the top of my head

1. (also your idea) Remove the extra class that (only?) Alpine needs OR
2. Add some text prominently in the documentation that makes people aware of the change
3. A user comments section on each module page (e.g. https://tailwindui.com/components/application-ui/application-shells/sidebar) kind of like the PHP documentation site might be useful. Instead of open commenting, just ones you approve (I know that would increase the burden on you, but it would prevent questions from being asked).

My head spins when thinking about all the cool user-contributed things we could do with TailwindUI components (such as a pre-built Vue, Ang, etc version submitted by users).

Looking forward to the next update!

**Comment by atomgiant** [comment]
This just bit me as well with Vue and the Stack Layout menu due to the hidden class:

`<div :class="{'block': open, 'hidden': !open}" class="hidden sm:hidden">`

The fix was to just remove the hidden class like so:

`<div :class="{'block': open, 'hidden': !open}" class="sm:hidden">`

I personally think it's fine for the Alpine examples to be written in the way that makes the most sense for Alpine.  I think something like a short conversion tips guide from Alpine to Vue would have been enough for me.  I wonder if you could even have the community maintain a quick guide in a public Git repo or something.

**Comment by jasonlbeggs** [comment]
Thanks for submitting this issue! I'm closing it now since Tailwind UI doesn't include any Alpine in the code snippets anymore.
