### ISSUE TITLE
Copy to clipboard on Safari paste everything inline

### ISSUE THREAD

**Issue by danieledistanio** [tailwindui/issues#8]
Copy/paste via Copy to clipboard on Safari on Mac paste everything inline, no breaks, no indentations.

This was confirmed on Discord by other users.

**Comment by adamwathan** [comment]
Hey thanks for reporting, this should be fixed now! 🙌 

For anyone curious, the way copy to clipboard works is we keep a copy of the component HTML in a hidden textarea, and we use `sr-only` + `aria-hidden` to keep it technically on screen but completely hidden from both sighted users and screenreader users. Part of the implementation of `sr-only` includes `whitespace: nowrap;` to prevent [words getting smushed together when read by screenreaders](https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe#.vcd5xlpgg), and in Safari, this was causing our examples to have their newlines removed.

Since we actually want the textarea hidden to _all_ users, the fix was just adding `whitespace-pre-wrap` to the textarea to force the line breaks to be preserved, and at no consequence to screenreader users since we hide this element from them with aria-hidden anyways.
