### ISSUE TITLE
@tailwindcss/ui and form elements and other extra classes

### ISSUE THREAD

**Issue by vesper8** [tailwindui/issues#84]
This is a question about the future of all of these form elements that are being used right now via @tailwindcss/ui

I was a bit surprised to find that these classes are being used through the components. It's my understanding that in order to use these templates we will not forever be obliged to pull in @tailwindcss/ui and that this is just a temporary measure until these classes get merged with tailwindcss

If I'm understanding that part correctly, then does that mean that all these form classes will be coming into the main tailwindcss branch ?

Right now I noticed that the tailwind-ui minified file is nearly 3x bigger than the tailwindcss one

711KB https://unpkg.com/tailwindcss@1.2.0/dist/tailwind.min.css
vs
1.8MB https://cdn.jsdelivr.net/npm/@tailwindcss/ui@latest/dist/tailwind-ui.min.css

What is all this extra stuff that we are now dependent on when we want to use the early access of Tailwind UI and will we really be able to do away with this extra dependency anytime soon?

**Comment by adamwathan** [comment]
Hey @vesper8!

The form elements come from the [@tailwindcss/custom-forms plugin](https://tailwindcss-custom-forms.netlify.com/) and are necessary because it's actually impossible to make things like checkboxes and radios "utility-stylable" without some pretty gnarly CSS changes. Think of it as basically a new base layer for form elements that make forms Tailwind-friendly so you can actually reliably style them with utilities. We even considered just applying those styles directly to form elements by default so you didn't even need to add classes like `form-input` or `form-checkbox` but ultimately felt too risky.

Basically without that plugin, form elements would be ugly and impossible for us to style.

Regardless though, the increase in file size is not because of the form styles — those only like 5kb, super small:

https://cdn.jsdelivr.net/npm/@tailwindcss/custom-forms@0.2.1/dist/custom-forms.min.css

The significant increase in file size is actually because of the number of theme extensions added by the `@tailwindcss/ui` plugin:

https://unpkg.com/browse/@tailwindcss/ui@0.1.3/index.js

The big things are adding things like `group-hover`, `group-focus`, `focus-within`, and `active` variants to many of the utilities, adding new colors, adding new box shadows, and adding a lot more to the spacing scale. Because Tailwind generates responsive/hover/etc. versions for all of this stuff it adds up really fast.

We are planning to migrate most of these extensions directly into Tailwind eventually, but that's just going to make Tailwind bigger by default as well, so losing the dependency isn't going to change the file size.

Your best bet is to use PurgeCSS to treeshake your styles for production, like we talk about in the Tailwind docs:

https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css

We only added things that were necessary to achieve the designs we put together so unfortunately there's nothing we can remove/disable that is generating unneeded styles right now.

If PurgeCSS isn't an option for your project, you can make a serious dent in the file size by removing colors you don't need, as those make up the vast majority of the file size 👍
